base:
  nameOverride: "redisinsight"
  fullnameOverride: "redisinsight"
  volumes:
    - name: db
      emptyDir: {}
      # If you want to use a PVC, set 'pvc.enabled: true' and uncomment the following lines and delete de previous one (emptyDir: {})
      # persistentVolumeClaim:
      #    claimName: storage-claim
  containers:
    - name: app
      image: "redislabs/redisinsight:1.14.0"
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 8001
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /healthcheck/
          port: 8001
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 2
      resources: {}
      volumeMounts:
        - name: db
          mountPath: /db

  upstream: "http://localhost:8001"

  cookieSecret: "bA7kPuPzko-igWaLPhVDWVj_VhENVnVcHce6rYQwu_s="

pvc:
  enabled: false
  size: 1Gi
