{{- $root := . -}}
{{ range $app := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $app.name }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
        {{- range $app.environments }}
          - {{ omit . "jwtTokens" | toYaml | indent 12 | trim }}        
        {{- end }}
  template:
    metadata:
      name: '{{`{{.argoApplicationName}}`}}'
    spec:
      project: '{{`{{.argoProjectName}}`}}'
      sources:
        - repoURL: '{{`{{.appGitopsRepoURL}}`}}'
          targetRevision: main
          path: '.'
          ref: values
        {{- if $.Values.applicationSetGlobal.baseChart }}
        - repoURL: {{  $.Values.applicationSetGlobal.baseChart.url | quote }}
          targetRevision: {{ $.Values.applicationSetGlobal.baseChart.targetRevision | quote }}
          {{- if $.Values.applicationSetGlobal.baseChart.chart }}
          chart: {{ $.Values.applicationSetGlobal.baseChart.chart | quote }}
          {{- end }}
          {{- if $.Values.applicationSetGlobal.baseChart.path }}
          path: {{ $.Values.applicationSetGlobal.baseChart.path | quote }}
          {{- end }}
          helm:
            valueFiles:
              - $values/values.yaml
        {{- end }}
      destination:
        server: '{{`{{.cluster}}`}}'
        namespace: '{{`{{.namespace}}`}}'
      {{- include "argocd-apps-root.syncPolicy" (dict "root" $root) | trim | nindent 6 }}
{{- end }}