apiVersion: v1
entries:
  openshift-secured-redisInsight:
  - apiVersion: v2
    created: "2023-07-11T15:33:06.1574424-03:00"
    description: A secured version of RedisInsight for OpenShift
    digest: bfbdffbd89303d1a07141a428b476ea42fdd2e856379782d7a4304302d3527ae
    name: openshift-secured-redisInsight
    type: application
    urls:
    - openshift-secured-redisInsight-0.1.0.tgz
    version: 0.1.0
generated: "2023-07-11T15:33:06.1519507-03:00"
