base:
  nameOverride: "redisinsight"
  fullnameOverride: "redisinsight"
  volumes:
    - name: db
      emptyDir: {}
  containers:
    - name: app
      image: "redislabs/redisinsight:1.14.0"
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 8001
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /healthcheck/
          port: 8001
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 2
      resources: {}
      volumeMounts:
        - name: db
          mountPath: /db

  upstream: http://localhost:8001

  cookieSecret: "bA7kPuPzko-igWaLPhVDWVj_VhENVnVcHce6rYQwu_s="
  