apiVersion: v2
name: argocd-apps-root
description: Chart para implementar el patrón app-of-apps de ArgoCD
type: application
version: 0.1.5
appVersion: 0.1.5
keywords:
  - openshift, argocd, app-of-apps
home: https://github.com/eximiait/charts
sources:
  - https://github.com/eximiait/charts/tree/main/argocd-apps-root
maintainers:
  - name: eximiait
    email: info.eximia.it@gmail.com
    url: https://www.eximiait.com.ar
annotations:
  artifacthub.io/changes: |
    - description: Se agrega metadata para artifacthub.io
      kind: Added
      version: 0.1.1
    - description: Se arregla problema de identación en list generator
      kind: Fixed
      version: 0.1.2
    - description: Se permite configurar globalmente namespaceResourceBlacklist,namespaceResourceWhitelist, clusterResourceWhitelist y clusterResourceBlacklist
      kind: Added
      version: 0.1.3
    - description: Ajuste manejo de values para el chart base
      kind: Fixed
      version: 0.1.4
    - description: Se agregan valores por defecto para el appProject
      kind: Added
      version: 0.1.5
