replicaCount: 1

image:
  repository: redislabs/redisinsight
  pullPolicy: IfNotPresent
  tag: 1.14.0

nameOverride: ""
fullnameOverride: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

rbac:
  namespaced: false # true habilita para que solamente se pueda acceder desde el namespace en el que se encuentra instalado

proxyExtraEnv: []
#   - --openshift-sar='{"namespace":"redis-insight","resource":"services","resourceName":"proxy","verb":"GET"}'

route:
  host: changeme.org