## Reference: https://github.com/helm/chart-testing-action
name: Linting
on: pull_request

permissions:
  contents: read

jobs:
  linter-artifacthub:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/artifacthub/ah:v1.14.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run ah lint
        working-directory: '.'
        run: ah lint